var data = {
    fruits: [{
        name: "香蕉",
        price: 3,
    }, {
        name: "苹果",
        price: 3,
    }, {
        name: "椰青",
        price: 32,
    }, {
        name: "火龙果",
        price: 40,
    }, {
        name: "哈密瓜",
        price: 45,
    }, {
        name: "西瓜",
        price: 30,
    }, {
        name: "榴莲",
        price: 159,
    }, {
        name: "香瓜",
        price: 26,
    }, {
        name: "奇异果",
        price: 139,
    }, {
        name: "蜜桃",
        price: 40,
    }, {
        name: "蓝莓",
        price: 10,
    }, {
        name: "脐橙",
        price: 70,
    }, {
        name: "百香果",
        price: 30,
    }, {
        name: "樱桃",
        price: 129,
    }],
    shucai: [{
        name: "大白菜",
        price: 0.3
    }, {
        name: "土豆",
        price: 1
    }, {
        name: "玉米",
        price: 2
    }, {
        name: "西红柿",
        price: 5
    }, {
        name: "豌豆",
        price: 2
    }, {
        name: "豆角",
        price: 3
    }, {
        name: "萝卜",
        price: 0.5
    }, {
        name: "芹菜",
        price: 6
    }, {
        name: "茄子",
        price: 4
    }, {
        name: "韭菜",
        price: 2
    }, {
        name: "南瓜",
        price: 6
    }, {
        name: "生菜",
        price: 2
    }, {
        name: "冬瓜",
        price: 8
    }]

}